### PR TITLE
Enochtsang/ac 19/postgres container

### PR DESCRIPTION
**Pull request by ExtraGravity**
@Right2Drive I don't actually know how to test if the application can interface with the DB. I checked that the application container could ping the postgres container, and also the db_name, db_user, and db_pass are the same.

### CODE REVIEW

**Review by jeinglis — DISMISSED** [review]
Looks good too me

**Comment by ExtraGravity** [comment]
@beaesguerra  please qa

**Comment by Parasrah** [comment]
Bea is away for another couple weeks @enochtsang

**Comment by ExtraGravity** [comment]
for when she comes back :)

**Comment by Parasrah** [comment]
Maybe we want to do away with the whole "stale review" thing?

**Review by Parasrah — APPROVED** [review]

**Pull request merged**
