### PR TITLE
Add option for backing up the database to file

### PR DESCRIPTION
**Pull request by ExtraGravity**
dockerize.sh script now has backupdb option to backup the current
database to a file. The database's name is based on the database name
and current datetime.

### CODE REVIEW

**Comment by mfalthaw** [comment]
@enochtsang Is it possible to see a demo of this tomorrow? This is very useful

**Comment by ExtraGravity** [comment]
Example file name is `agricore_dev.sql.2018-10-21_21-34-54`

**Comment by ExtraGravity** [comment]
But ya, I was just thinking of how we were deploying soon, and how terrified I am of us losing their data.

**Comment by mfalthaw** [comment]
Let's test it on a dummy db tomorrow

**Review by mfalthaw — APPROVED** [review]

**Pull request merged**
