### PR TITLE
Add password salt in database and fix comments

### PR DESCRIPTION
**Pull request by ExtraGravity**
Add password salt in database schema for authentication.
Change password comments to passwordHash since passwords
won't be stored in the database, only their hashes.

### CODE REVIEW

**Comment by Parasrah** [comment]
Hey, there just needs to be a single field in the database for a hash. No salt, the salt is stored as part of the hash

**Comment by ExtraGravity** [comment]
How is the password salted?

**Comment by Parasrah** [comment]
@enochtsang https://stackoverflow.com/questions/6832445/how-can-bcrypt-have-built-in-salts#6833165

**Comment by ExtraGravity** [comment]
Interesting, so i should rename passwordHash to hash and call it a day.

**Review by Parasrah — APPROVED** [review]

**Pull request merged**
